
services:
  influxdb:
    image: influxdb:2-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=StrongPassword123!
      - DOCKER_INFLUXDB_INIT_ORG=main-org
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=SuperSecretToken456!
    networks:
      - app_net
      - web_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.influxdb.entrypoints=http
      - traefik.http.routers.influxdb.rule=Host(`${INFLUX_SUBDOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.influxdb.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.influxdb-secure.entrypoints=https
      - traefik.http.routers.influxdb-secure.rule=Host(`${INFLUX_SUBDOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.influxdb-secure.tls=true
      - traefik.http.routers.influxdb-secure.tls.options=default
      - traefik.http.routers.influxdb-secure.tls.certresolver=mycert
      - traefik.http.services.influxdb.loadbalancer.server.port=8086

  app:
    image: node:20
    container_name: typescript-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - influxdb
    networks:
      - app_net

  k6:
    build: .
    container_name: k6-runner
    networks:
      - app_net
    environment:
      - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=main-org
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_INSECURE=true
      - K6_INFLUXDB_TOKEN=SuperSecretToken456!
    volumes:
      - /tests:/home/k6user/tests
    working_dir: /home/k6user
    command: run tests/idea/test.ts -o xk6-influxdb

volumes:
  influxdb_data:

networks:
  app_net:
    driver: bridge
  web_net:
    external: true