version: "3.8"

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    networks:
      - app_net
      - web_net

  app:
    image: node:20
    container_name: typescript-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - influxdb
    networks:
      - app_net

  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    container_name: k6-runner
    working_dir: /tests
    volumes:
      - ./tests:/tests
    depends_on:
      - influxdb
    networks:
      - app_net

volumes:
  influxdb_data:

networks:
  app_net:
    external: false
    name: app_net
  web_net:
    external: true
    name: web_net
