FROM golang:1.21 AS builder

WORKDIR /src

RUN go install go.k6.io/xk6/cmd/xk6@latest

RUN xk6 build --with github.com/grafana/xk6-output-influxdb@latest

FROM debian:bullseye-slim

COPY --from=builder /src/k6 /usr/bin/k6

ENTRYPOINT ["k6"]
